"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
	async up(queryInterface, Sequelize) {
		const currentYear = new Date().getFullYear();
		await queryInterface.bulkInsert(
			"Anggota",
			[
				{
					id_token: `A1B2C3D4`,
					nama_lengkap: "Ike Ineke Suwanda",
					nama_panggilan: "Ike",
					email: "ike.suwanda@example.com",
					tempat_lahir: "Bandung",
					tanggal_lahir: new Date("1970-05-15"),
					jenis_kelamin: "Perempuan",
					alamat: "Jl. Cikutra No. 1, Bandung",
					agama: "Islam",
					no_telepon: "081234567890",
					angkatan_unit: "Pendiri",
					status_keanggotaan: "Aktif",
					status_perguruan: "Guru Besar",
					tingkatan_sabuk: "Sabuk Merah Strip Emas",
					foto: null,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
        
				{
					id_token: `E5F6G7H8`,
					nama_lengkap: "E. Tholib",
					nama_panggilan: "Tholib",
					email: "e.tholib@example.com",
					tempat_lahir: "Jakarta",
					tanggal_lahir: new Date("1972-08-20"),
					jenis_kelamin: "Laki-laki",
					alamat: "Jl. Sudirman No. 2, Jakarta",
					agama: "Islam",
					no_telepon: "081234567891",
					angkatan_unit: "Pendiri",
					status_keanggotaan: "Aktif",
					status_perguruan: "Guru Besar",
					tingkatan_sabuk: "Sabuk Merah Strip Emas",
					foto: null,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				{
					id_token: `I9J1K2L3`,
					nama_lengkap: "Moh. Ramdhan",
					nama_panggilan: "Ramdhan",
					email: "moh.ramdhan@example.com",
					tempat_lahir: "Surabaya",
					tanggal_lahir: new Date("2000-01-10"),
					jenis_kelamin: "Laki-laki",
					alamat: "Jl. Pahlawan No. 3, Surabaya",
					agama: "Islam",
					no_telepon: "081234567892",
					angkatan_unit: "Angkatan 2018",
					status_keanggotaan: "Aktif",
					status_perguruan: "Anggota",
					tingkatan_sabuk: "Sabuk Hijau",
					foto: null,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				{
					id_token: `M4N5O6P7`,
					nama_lengkap: "Ratih Komalasari",
					nama_panggilan: "Ratih",
					email: "ratih.k@example.com",
					tempat_lahir: "Bandung",
					tanggal_lahir: new Date("1995-11-25"),
					jenis_kelamin: "Perempuan",
					alamat: "Jl. Asia Afrika No. 4, Bandung",
					agama: "Islam",
					no_telepon: "081234567893",
					angkatan_unit: "Angkatan 2013",
					status_keanggotaan: "Aktif",
					status_perguruan: "Pelatih",
					tingkatan_sabuk: "Sabuk Merah",
					foto: null,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				{
					id_token: `Q8R9S1T2`,
					nama_lengkap: "Rifki Fajari Supriatna",
					nama_panggilan: "Rifki",
					email: "rifki.fs@example.com",
					tempat_lahir: "Cimahi",
					tanggal_lahir: new Date("1996-03-12"),
					jenis_kelamin: "Laki-laki",
					alamat: "Jl. Gatot Subroto No. 5, Cimahi",
					agama: "Islam",
					no_telepon: "081234567894",
					angkatan_unit: "Angkatan 2014",
					status_keanggotaan: "Aktif",
					status_perguruan: "Pelatih",
					tingkatan_sabuk: "Sabuk Merah",
					foto: null,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				{
					id_token: `U3V4W5X6`,
					nama_lengkap: "Yogi Nugraha",
					nama_panggilan: "Yogi",
					email: "yogi.nugraha@example.com",
					tempat_lahir: "Bandung",
					tanggal_lahir: new Date("1997-07-07"),
					jenis_kelamin: "Laki-laki",
					alamat: "Jl. Setiabudi No. 6, Bandung",
					agama: "Islam",
					no_telepon: "081234567895",
					angkatan_unit: "Angkatan 2015",
					status_keanggotaan: "Aktif",
					status_perguruan: "Pelatih",
					tingkatan_sabuk: "Sabuk Coklat",
					foto: null,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				{
					id_token: `Y7Z8A9B1`,
					nama_lengkap: "M. Rafi Ramadhan",
					nama_panggilan: "Rafi",
					email: "m.rafi.r@example.com",
					tempat_lahir: "Jakarta",
					tanggal_lahir: new Date("1998-09-18"),
					jenis_kelamin: "Laki-laki",
					alamat: "Jl. Kebon Jeruk No. 7, Jakarta",
					agama: "Islam",
					no_telepon: "081234567896",
					angkatan_unit: "Angkatan 2016",
					status_keanggotaan: "Aktif",
					status_perguruan: "Pelatih",
					tingkatan_sabuk: "Sabuk Coklat",
					foto: null,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				{
					id_token: `C2D3E4F5`,
					nama_lengkap: "Adinda Dara Sentifa",
					nama_panggilan: "Adinda",
					email: "adinda.ds@example.com",
					tempat_lahir: "Yogyakarta",
					tanggal_lahir: new Date("1999-04-22"),
					jenis_kelamin: "Perempuan",
					alamat: "Jl. Malioboro No. 8, Yogyakarta",
					agama: "Islam",
					no_telepon: "081234567897",
					angkatan_unit: "Angkatan 2017",
					status_keanggotaan: "Aktif",
					status_perguruan: "Pelatih",
					tingkatan_sabuk: "Sabuk Coklat",
					foto: null,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				{
					id_token: `G6H7I8J9`,
					nama_lengkap: "Rizky Muhammad Sujaya",
					nama_panggilan: "Rizky",
					email: "rizky.ms@example.com",
					tempat_lahir: "Bandung",
					tanggal_lahir: new Date("1998-12-30"),
					jenis_kelamin: "Laki-laki",
					alamat: "Jl. Dago No. 9, Bandung",
					agama: "Islam",
					no_telepon: "081234567898",
					angkatan_unit: "Angkatan 2016",
					status_keanggotaan: "Aktif",
					status_perguruan: "Pelatih",
					tingkatan_sabuk: "Sabuk Coklat",
					foto: null,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				{
					id_token: `K1L2M3N4`,
					nama_lengkap: "Budi Santoso",
					nama_panggilan: "Budi",
					email: "budi.santoso@example.com",
					tempat_lahir: "Semarang",
					tanggal_lahir: new Date("2001-02-14"),
					jenis_kelamin: "Laki-laki",
					alamat: "Jl. Simpang Lima No. 10, Semarang",
					agama: "Islam",
					no_telepon: "081234567899",
					angkatan_unit: "Angkatan 2019",
					status_keanggotaan: "Aktif",
					status_perguruan: "Anggota",
					tingkatan_sabuk: "Sabuk Kuning",
					foto: null,
					createdAt: new Date(),
					updatedAt: new Date(),
				},
			],
			{}
		);
	},

	async down(queryInterface, Sequelize) {
		await queryInterface.bulkDelete("Anggota", null, {});
	},
};

