"use strict";

module.exports = {
	async up(queryInterface, Sequelize) {
		await queryInterface.bulkInsert(
			"Anggota",
			[
				// 1. Data Anggota untuk User ID 2
				{
					id_user: 1,
					id_token: "7B4W9P2X",
					tempat_lahir: "Jakarta",
					tanggal_lahir: new Date("1998-05-10"),
					jenis_kelamin: "Laki-laki",
					alamat: "Jl. Merdeka No. 10, Jakarta",
					agama: "Islam",
					no_telepon: "081234567890",
					angkatan_unit: "2018",
					status_keanggotaan: "Aktif",
					status_perguruan: "Anggota",
					tingkatan_sabuk: "Belum punya",
					foto: "",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				// 2. Data Anggota untuk User ID 3
				{
					id_user: 2,
					id_token: "K8F3Z6HJ",
					tempat_lahir: "Bandung",
					tanggal_lahir: new Date("2000-11-22"),
					jenis_kelamin: "Perempuan",
					alamat: "Jl. Asia Afrika No. 25, Bandung",
					agama: "Islam",
					no_telepon: "081298765432",
					angkatan_unit: "2020",
					status_keanggotaan: "Aktif",
					status_perguruan: "Anggota",
					tingkatan_sabuk: "Belum punya",
					foto: "",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				// 3. Data Anggota untuk User ID 4
				{
					id_user: 3,
					id_token: "R5M1N9QC",
					tempat_lahir: "Surabaya",
					tanggal_lahir: new Date("1999-01-15"),
					jenis_kelamin: "Laki-laki",
					alamat: "Jl. Tunjungan No. 5, Surabaya",
					agama: "Kristen",
					no_telepon: "081311223344",
					angkatan_unit: "2019",
					status_keanggotaan: "Aktif",
					status_perguruan: "Anggota",
					tingkatan_sabuk: "Belum punya",
					foto: "",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				// 4. Data Anggota untuk User ID 5
				{
					id_user: 4,
					id_token: "A2D7G6VT",
					tempat_lahir: "Yogyakarta",
					tanggal_lahir: new Date("2001-07-30"),
					jenis_kelamin: "Perempuan",
					alamat: "Jl. Malioboro No. 1, Yogyakarta",
					agama: "Islam",
					no_telepon: "081455667788",
					angkatan_unit: "2021",
					status_keanggotaan: "Aktif",
					status_perguruan: "Anggota",
					tingkatan_sabuk: "Belum punya",
					foto: "",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				// 5. Data Anggota untuk User ID 6
				{
					id_user: 5,
					id_token: "Y4S9L3PK",
					tempat_lahir: "Medan",
					tanggal_lahir: new Date("1997-03-25"),
					jenis_kelamin: "Laki-laki",
					alamat: "Jl. Gatot Subroto No. 100, Medan",
					agama: "Buddha",
					no_telepon: "081599887766",
					angkatan_unit: "2017",
					status_keanggotaan: "Aktif",
					status_perguruan: "Anggota",
					tingkatan_sabuk: "Belum punya",
					foto: "",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				// 6. Data Anggota untuk User ID 7
				{
					id_user: 6,
					id_token: "E6Z8W1XN",
					tempat_lahir: "Semarang",
					tanggal_lahir: new Date("2002-09-05"),
					jenis_kelamin: "Perempuan",
					alamat: "Jl. Pahlawan No. 2, Semarang",
					agama: "Islam",
					no_telepon: "081612345678",
					angkatan_unit: "2022",
					status_keanggotaan: "Aktif",
					status_perguruan: "Anggota",
					tingkatan_sabuk: "Belum punya",
					foto: "",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				// 7. Data Anggota untuk User ID 8
				{
					id_user: 7,
					id_token: "C3V5B7TM",
					tempat_lahir: "Makassar",
					tanggal_lahir: new Date("1996-12-12"),
					jenis_kelamin: "Laki-laki",
					alamat: "Jl. Losari No. 8, Makassar",
					agama: "Katolik",
					no_telepon: "081787654321",
					angkatan_unit: "2016",
					status_keanggotaan: "Aktif",
					status_perguruan: "Anggota",
					tingkatan_sabuk: "Belum punya",
					foto: "",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				// 8. Data Anggota untuk User ID 9
				{
					id_user: 8,
					id_token: "J9H2R4DF",
					tempat_lahir: "Palembang",
					tanggal_lahir: new Date("2003-02-20"),
					jenis_kelamin: "Perempuan",
					alamat: "Jl. Jenderal Sudirman No. 9, Palembang",
					agama: "Islam",
					no_telepon: "081811112222",
					angkatan_unit: "2023",
					status_keanggotaan: "Aktif",
					status_perguruan: "Anggota",
					tingkatan_sabuk: "Belum punya",
					foto: "",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				// 9. Data Anggota untuk User ID 10
				{
					id_user: 9,
					id_token: "P7Q6K1S",
					tempat_lahir: "Denpasar",
					tanggal_lahir: new Date("2000-08-17"),
					jenis_kelamin: "Laki-laki",
					alamat: "Jl. Kuta Raya No. 10, Denpasar",
					agama: "Hindu",
					no_telepon: "081933334444",
					angkatan_unit: "2020",
					status_keanggotaan: "Aktif",
					status_perguruan: "Anggota",
					tingkatan_sabuk: "Belum punya",
					foto: "",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
			],
			{}
		);
	},

	async down(queryInterface, Sequelize) {
		await queryInterface.bulkDelete("Anggota", null, {});
	},
};

