"use strict";
const bcrypt = require("bcrypt");

module.exports = {
	async up(queryInterface, Sequelize) {
		const hashedPassword = bcrypt.hashSync("password123", 10);

		await queryInterface.bulkInsert(
			"Anggota",
			[
				// 1. Data Anggota untuk User ID 1 (Admin Utama - Admin)
				{
					nama: "Admin Utama",
					email: "admin@test.com",
					password: bcrypt.hashSync("admin123", 10),
					role: "admin",
					id_token: "7B4W9P2X",
					tempat_lahir: "Jakarta",
					tanggal_lahir: new Date("1998-05-10"),
					jenis_kelamin: "Laki-laki",
					alamat: "Jl. Merdeka No. 10, Jakarta",
					agama: "Islam",
					no_telepon: "081234567890",
					angkatan_unit: "2018",
					status_keanggotaan: "Aktif",
					status_perguruan: "Anggota",
					tingkatan_sabuk: "Belum punya",
					foto: "",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				// 2. Data Anggota untuk User ID 2 (Ike Ineke Suwanda - Guru Besar)
				{
					nama: "Ike Ineke Suwanda",
					email: "ike.ineke.suwanda@example.com",
					password: hashedPassword,
					role: "anggota",
					id_token: "K8F3Z6HJ",
					tempat_lahir: "Bandung",
					tanggal_lahir: new Date("2000-11-22"),
					jenis_kelamin: "Perempuan",
					alamat: "Jl. Asia Afrika No. 25, Bandung",
					agama: "Islam",
					no_telepon: "081298765432",
					angkatan_unit: "2020",
					status_keanggotaan: "Aktif",
					status_perguruan: "Guru Besar",
					tingkatan_sabuk: "Belum punya",
					foto: "",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				// 3. Data Anggota untuk User ID 3 (E. Tholib - Guru Besar)
				{
					nama: "E. Tholib",
					email: "e.tholib@example.com",
					password: hashedPassword,
					role: "anggota",
					id_token: "R5M1N9QC",
					tempat_lahir: "Surabaya",
					tanggal_lahir: new Date("1999-01-15"),
					jenis_kelamin: "Laki-laki",
					alamat: "Jl. Tunjungan No. 5, Surabaya",
					agama: "Islam",
					no_telepon: "081311223344",
					angkatan_unit: "2019",
					status_keanggotaan: "Aktif",
					status_perguruan: "Guru Besar",
					tingkatan_sabuk: "Belum punya",
					foto: "",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				// 4. Data Anggota untuk User ID 4 (Moh. Ramdhan - Pelatih)
				{
					nama: "Moh. Ramdhan",
					email: "moh.ramdhan@example.com",
					password: hashedPassword,
					role: "anggota",
					id_token: "A2D7G6VT",
					tempat_lahir: "Bandung",
					tanggal_lahir: new Date("1990-05-25"),
					jenis_kelamin: "Laki-laki",
					alamat: "Kp. Ciganitri, Desa Cipagalo, Kec. Bojongsoang ,Kab. Bandung",
					agama: "Islam",
					no_telepon: "082118534150",
					angkatan_unit: "26",
					status_keanggotaan: "Aktif",
					status_perguruan: "Pelatih",
					tingkatan_sabuk: "Belum punya",
					foto: "",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				// 5. Data Anggota untuk User ID 5 (Ratih Komalasari - Pelatih)
				{
					nama: "Ratih Komalasari",
					email: "ratih.komalasari@example.com",
					password: hashedPassword,
					role: "anggota",
					id_token: "Y4S9L3PK",
					tempat_lahir: "Bandung",
					tanggal_lahir: new Date("1999-10-06"),
					jenis_kelamin: "Perempuan",
					alamat: "Kp. Gunungleutik, Ciparay Kab. Bandung",
					agama: "Islam",
					no_telepon: "082126149981",
					angkatan_unit: "35",
					status_keanggotaan: "Aktif",
					status_perguruan: "Pelatih",
					tingkatan_sabuk: "Sabuk Merah",
					foto: "",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				// 6. Data Anggota untuk User ID 6 (Rifki Fajari Supriatna - Pelatih)
				{
					nama: "Rifki Fajari Supriatna",
					email: "rifki.fajari.supriatna@example.com",
					password: hashedPassword,
					role: "anggota",
					id_token: "E6Z8W1XN",
					tempat_lahir: "Bandung",
					tanggal_lahir: new Date("1999-09-13"),
					jenis_kelamin: "Laki-laki",
					alamat: "Jl. Antabaru Dalam 2 No 5, Kota Bandung",
					agama: "Islam",
					no_telepon: "081612345678",
					angkatan_unit: "35",
					status_keanggotaan: "Aktif",
					status_perguruan: "Pelatih",
					tingkatan_sabuk: "Sabuk Merah",
					foto: "",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				// 7. Data Anggota untuk User ID 7 (Yogi Nugraha - Pelatih)
				{
					nama: "Yogi Nugraha",
					email: "yogi.nugraha@example.com",
					password: hashedPassword,
					role: "anggota",
					id_token: "C3V5B7TM",
					tempat_lahir: "Makassar",
					tanggal_lahir: new Date("1996-12-12"),
					jenis_kelamin: "Laki-laki",
					alamat: "Jl. Losari No. 8, Makassar",
					agama: "Islam",
					no_telepon: "081787654321",
					angkatan_unit: "2016",
					status_keanggotaan: "Aktif",
					status_perguruan: "Pelatih",
					tingkatan_sabuk: "Belum punya",
					foto: "",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				// 8. Data Anggota untuk User ID 9 (M. Rafi Ramadhan - Pelatih)
				{
					nama: "M. Rafi Ramadhan",
					email: "m.rafi.ramadhan@example.com",
					password: hashedPassword,
					role: "anggota",
					id_token: "J9H2R4DF",
					tempat_lahir: "Bandung",
					tanggal_lahir: new Date("1994-02-18"),
					jenis_kelamin: "Laki-laki",
					alamat:
						"Kp. Babakan Sadang RT 03 RW 11, Andir, Baleendah, Kab. Bandung",
					agama: "Islam",
					no_telepon: "085724000394",
					angkatan_unit: "30",
					status_keanggotaan: "Aktif",
					status_perguruan: "Pelatih",
					tingkatan_sabuk: "Sabuk Merah",
					foto: "",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				// 9. Data Anggota untuk User ID 9 (Adinda Dara Sentifa - Pelatih)
				{
					nama: "Adinda Dara Sentifa",
					email: "adinda.dara.sentifa@example.com",
					password: hashedPassword,
					role: "anggota",
					id_token: "P7Q6K1S",
					tempat_lahir: "Bandung",
					tanggal_lahir: new Date("1998-02-16"),
					jenis_kelamin: "Perempuan",
					alamat:
						"Kp. Babakan Sadang RT 03 RW 11, Andir, Baleendah, Kab. Bandung",
					agama: "Islam",
					no_telepon: "085721766265",
					angkatan_unit: "30",
					status_keanggotaan: "Aktif",
					status_perguruan: "Pelatih",
					tingkatan_sabuk: "Sabuk Merah",
					foto: "",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
				// 10. Data Anggota untuk User ID 11 (Rizky Muhammad Sujaya - Pelatih)
				{
					nama: "Rizky Muhammad Sujaya",
					email: "rizky.muhammad.sujaya@example.com",
					password: hashedPassword,
					role: "anggota",
					id_token: "F7M6G1S",
					tempat_lahir: "Denpasar",
					tanggal_lahir: new Date("2000-08-17"),
					jenis_kelamin: "Laki-laki",
					alamat: "Jl. Kuta Raya No. 10, Denpasar",
					agama: "Islam",
					no_telepon: "081933334224",
					angkatan_unit: "2020",
					status_keanggotaan: "Aktif",
					status_perguruan: "Pelatih",
					tingkatan_sabuk: "Belum punya",
					foto: "",
					createdAt: new Date(),
					updatedAt: new Date(),
				},
			],
			{}
		);
	},

	async down(queryInterface, Sequelize) {
		await queryInterface.bulkDelete("Anggota", null, {});
	},
};

